import type { CommandEntry } from "@/types/db2";

export const DB2_COMMANDS: CommandEntry[] = [
  {
    id: "db2pd-locks",
    name: "db2pd -locks",
    fullSyntax: "db2pd -db <DBNAME> -locks [showlocks] [-applications]",
    description: "Real-time lock diagnostics from shared memory. No catalog locking overhead. The primary tool for lock incident triage.",
    category: "Diagnostics",
    flags: [
      { flag: "-db <DBNAME>", description: "Scope to a specific database" },
      { flag: "showlocks", description: "Show full lock detail per lock record (holder, mode, object)" },
      { flag: "-applications", description: "Also show application connection details — correlates AppHandle to conn info" },
      { flag: "-interval <n>", description: "Loop: re-sample every n seconds" },
      { flag: "-count <n>", description: "Number of samples to take (use with -interval)" },
    ],
    examples: [
      { command: "db2pd -db PRODDB -locks showlocks -applications", description: "Full lock diagnostic: identify holder and all waiters in one pass" },
      { command: "db2pd -db PRODDB -locks showlocks -interval 5 -count 6", description: "Monitor lock state every 5 seconds for 30 seconds" },
    ],
    relatedConceptIds: ["locking", "deadlocks", "lock-escalation"],
    recallScenario: "15 application threads are blocked. You have 30 seconds to find the lock holder before the on-call manager escalates. What command do you run?",
    difficulty: 1,
  },
  {
    id: "db2pd-hadr",
    name: "db2pd -hadr",
    fullSyntax: "db2pd -db <DBNAME> -hadr",
    description: "Real-time HADR state: synchronization mode, log positions, gap, connect status. Run on both primary and standby.",
    category: "HADR",
    flags: [
      { flag: "-db <DBNAME>", description: "Database name" },
    ],
    examples: [
      { command: "db2pd -db PRODDB -hadr", description: "Primary-side HADR state", output: "HADR_STATE=PEER HADR_SYNCMODE=NEARSYNC LOG_GAP_RUNNING_TOTAL=0 HADR_CONNECT_STATUS=CONNECTED" },
      { command: "db2pd -db STBYDB -hadr", description: "Standby-side HADR state — shows replay progress" },
    ],
    relatedConceptIds: ["hadr", "transaction-logging"],
    recallScenario: "HADR alert fires at 3am. You need to confirm HADR state, sync mode, and whether the gap is growing. Single command.",
    difficulty: 1,
  },
  {
    id: "db2pd-transactions",
    name: "db2pd -transactions",
    fullSyntax: "db2pd -db <DBNAME> -transactions",
    description: "Shows all active transactions, their first log record (FirstLSN — shows how long a transaction is open and how much log space it holds).",
    category: "Diagnostics",
    flags: [
      { flag: "-db <DBNAME>", description: "Database name" },
    ],
    examples: [
      { command: "db2pd -db PRODDB -transactions", description: "Find long-running transactions holding log space", output: "TranHdl=142 AppHdl=0-34892 FirstLSN=0x1A3B CurrentLSN=0x2F1C State=WRITE" },
    ],
    relatedConceptIds: ["transaction-logging", "locking"],
    recallScenario: "SQL0964C is firing. Filesystem is not full. How do you identify which application is consuming all log space?",
    difficulty: 2,
  },
  {
    id: "db2pd-logs",
    name: "db2pd -logs",
    fullSyntax: "db2pd -db <DBNAME> -logs",
    description: "Log space utilization: current log file, primary/secondary log usage, log path, archive status.",
    category: "Diagnostics",
    flags: [],
    examples: [
      { command: "db2pd -db PRODDB -logs", description: "Check log space before and during high-volume batch operations" },
    ],
    relatedConceptIds: ["transaction-logging", "archive-logging"],
    recallScenario: "Log full alert fires. You need to see log space utilization, current log file, and secondary log usage immediately.",
    difficulty: 1,
  },
  {
    id: "mon-get-database",
    name: "MON_GET_DATABASE",
    fullSyntax: "SELECT <cols> FROM TABLE(MON_GET_DATABASE(-2)) AS T",
    description: "Aggregate database-level metrics: log utilization, sorts, connections, buffer pool totals. The widest single-query diagnostic view.",
    category: "Monitoring SQL",
    flags: [
      { flag: "-2", description: "Aggregate across all members (use member number 0,1,2... for specific member)" },
    ],
    examples: [
      { command: "SELECT LOG_UTILIZATION_PERCENT, TOTAL_LOG_USED_KB, TOTAL_LOG_AVAILABLE_KB, SORT_OVERFLOWS, TOTAL_SORTS, NUM_COMPILATIONS, CONNECTIONS_TOP FROM TABLE(MON_GET_DATABASE(-2)) AS T", description: "Health dashboard — log, sort, compilation, connections at a glance" },
    ],
    relatedConceptIds: ["mon-get", "transaction-logging", "sort-heap"],
    recallScenario: "You have 60 seconds to assess overall database health. Write the SQL query.",
    difficulty: 2,
  },
  {
    id: "mon-get-activity",
    name: "MON_GET_ACTIVITY",
    fullSyntax: "SELECT <cols> FROM TABLE(MON_GET_ACTIVITY(NULL,-2)) AS T",
    description: "Currently executing SQL statements with application handle, elapsed time, and statement text.",
    category: "Monitoring SQL",
    flags: [],
    examples: [
      { command: "SELECT APPLICATION_HANDLE, ELAPSED_TIME_SEC, LEFT(STMT_TEXT,120) AS SQL FROM TABLE(MON_GET_ACTIVITY(NULL,-2)) AS T ORDER BY ELAPSED_TIME_SEC DESC FETCH FIRST 10 ROWS ONLY", description: "Top 10 longest-running SQL statements right now" },
    ],
    relatedConceptIds: ["mon-get", "performance-explain"],
    recallScenario: "Users complain queries are slow. Find the currently-running SQL taking longest.",
    difficulty: 2,
  },
  {
    id: "explain-plan",
    name: "EXPLAIN PLAN / db2exfmt",
    fullSyntax: "SET CURRENT EXPLAIN MODE EXPLAIN; <SQL>; SET CURRENT EXPLAIN MODE NO; -- then: db2exfmt -d <DB> -1 -o plan.txt",
    description: "Capture optimizer access plan without executing. db2exfmt formats EXPLAIN tables into readable plan tree.",
    category: "Performance",
    flags: [
      { flag: "-d <DBNAME>", description: "Database name" },
      { flag: "-e <schema>", description: "Explain schema (default: current user)" },
      { flag: "-1", description: "Format most recent explain" },
      { flag: "-o <file>", description: "Output file" },
    ],
    examples: [
      { command: "db2exfmt -d PRODDB -1 -o /tmp/plan.txt && cat /tmp/plan.txt", description: "Format and display the most recent explain" },
    ],
    relatedConceptIds: ["performance-explain", "statistics", "index-strategy"],
    recallScenario: "A specific query is slow. You want to see its access plan without waiting for it to run. Describe the two-step process.",
    difficulty: 2,
  },
  {
    id: "runstats",
    name: "RUNSTATS",
    fullSyntax: "RUNSTATS ON TABLE <schema>.<table> WITH DISTRIBUTION AND INDEXES ALL [SHRLEVEL CHANGE]",
    description: "Collect optimizer statistics: table cardinality, column distributions, index statistics. SHRLEVEL CHANGE allows online concurrent DML.",
    category: "Administration",
    flags: [
      { flag: "WITH DISTRIBUTION", description: "Collect column value frequency histograms — critical for skewed data" },
      { flag: "AND INDEXES ALL", description: "Collect statistics for all indexes on the table" },
      { flag: "SHRLEVEL CHANGE", description: "Allow concurrent reads AND writes during RUNSTATS" },
      { flag: "TABLESAMPLE SYSTEM(n)", description: "Sample n% of pages — faster for very large tables" },
    ],
    examples: [
      { command: "RUNSTATS ON TABLE TRADING.ORDERS WITH DISTRIBUTION AND INDEXES ALL SHRLEVEL CHANGE", description: "Full online RUNSTATS on ORDERS table" },
      { command: "RUNSTATS ON TABLE BIG.FACT_TABLE TABLESAMPLE SYSTEM(20) WITH DISTRIBUTION AND INDEXES ALL", description: "Sampled RUNSTATS for a very large fact table (20% sample)" },
    ],
    relatedConceptIds: ["statistics", "performance-explain", "package-cache"],
    recallScenario: "Explain plan shows NCARD=1 on a table with 50 million rows. What command do you run, including all recommended options?",
    difficulty: 1,
  },
  {
    id: "backup-database",
    name: "BACKUP DATABASE",
    fullSyntax: "BACKUP DATABASE <name> [ONLINE] TO <path> [COMPRESS] [INCLUDE LOGS] [WITHOUT PROMPTING]",
    description: "Take a database backup. ONLINE allows backup while database is accessible. COMPRESS reduces image size. INCLUDE LOGS embeds needed logs in the image.",
    category: "Backup & Recovery",
    flags: [
      { flag: "ONLINE", description: "Database remains accessible during backup (requires archive logging)" },
      { flag: "COMPRESS", description: "Compress backup image — typically 50-70% size reduction" },
      { flag: "INCLUDE LOGS", description: "Embed archive logs in image — self-contained for rollforward" },
      { flag: "WITHOUT PROMPTING", description: "Non-interactive — required for scripted/cron backups" },
      { flag: "INCREMENTAL DELTA", description: "Only pages changed since last backup (requires baseline full backup)" },
    ],
    examples: [
      { command: "BACKUP DATABASE PRODDB ONLINE TO /db2backup COMPRESS INCLUDE LOGS WITHOUT PROMPTING", description: "Standard production online backup" },
      { command: "BACKUP DATABASE PRODDB ONLINE INCREMENTAL DELTA TO /db2backup COMPRESS WITHOUT PROMPTING", description: "Incremental delta backup" },
    ],
    relatedConceptIds: ["backup", "archive-logging", "restore-rollforward"],
    recallScenario: "Write the BACKUP command for a production database requiring: online, compressed, self-contained for restore, non-interactive for cron.",
    difficulty: 1,
  },
  {
    id: "rollforward",
    name: "ROLLFORWARD DATABASE",
    fullSyntax: "ROLLFORWARD DATABASE <name> TO [END OF LOGS | <timestamp>] [AND STOP] [TABLESPACE (<ts1>,<ts2>)]",
    description: "Replay archive and active logs after RESTORE. TO END OF LOGS applies all available logs. TO <timestamp> is point-in-time recovery. AND STOP brings database online.",
    category: "Backup & Recovery",
    flags: [
      { flag: "TO END OF LOGS", description: "Replay all available logs — full recovery" },
      { flag: "TO <timestamp>", description: "Point-in-time recovery: format YYYY-MM-DD-HH.MM.SS.NNNNNN" },
      { flag: "AND STOP", description: "Complete rollforward and bring database/tablespace online" },
      { flag: "TABLESPACE (<name>)", description: "Rollforward only specific tablespace(s)" },
      { flag: "QUERY STATUS", description: "Check rollforward progress without advancing" },
    ],
    examples: [
      { command: "ROLLFORWARD DATABASE PRODDB TO END OF LOGS AND STOP", description: "Full recovery — apply all logs and bring online" },
      { command: "ROLLFORWARD DATABASE PRODDB TO 2024-03-14-09.00.00.000000 AND STOP", description: "Point-in-time recovery to 09:00 UTC on 14 March 2024" },
      { command: "ROLLFORWARD DATABASE PRODDB QUERY STATUS", description: "Check progress — shows current log position and minimum recovery time" },
    ],
    relatedConceptIds: ["restore-rollforward", "archive-logging", "transaction-logging"],
    recallScenario: "After a RESTORE, you need to apply all logs and bring the database online. Write the ROLLFORWARD command.",
    difficulty: 1,
  },
  {
    id: "takeover-hadr",
    name: "TAKEOVER HADR",
    fullSyntax: "TAKEOVER HADR ON DATABASE <name> [BY FORCE]",
    description: "Promote standby to primary. Without BY FORCE: requires PEER state (planned takeover, zero data loss). BY FORCE: override — use ONLY when primary is confirmed dead.",
    category: "HADR",
    flags: [
      { flag: "BY FORCE", description: "Takeover regardless of HADR state. WARNING: split brain risk if primary is still running." },
    ],
    examples: [
      { command: "TAKEOVER HADR ON DATABASE PRODDB", description: "Planned graceful takeover — waits for PEER state" },
      { command: "TAKEOVER HADR ON DATABASE PRODDB BY FORCE", description: "Emergency: primary confirmed dead and unreachable" },
    ],
    relatedConceptIds: ["hadr", "transaction-logging"],
    recallScenario: "Primary datacenter is down, all connectivity lost. Primary DB2 confirmed dead by network team. Walk through the takeover procedure.",
    difficulty: 3,
  },
  {
    id: "force-application",
    name: "FORCE APPLICATION",
    fullSyntax: "db2 \"FORCE APPLICATION (<apphandle>)\" or FORCE APPLICATION ALL",
    description: "Forcibly disconnect an application. DB2 initiates transaction rollback for the forced connection. Use to resolve lock holders or long-running transactions.",
    category: "Administration",
    flags: [
      { flag: "(<apphandle>)", description: "Force specific application by handle (from LIST APPLICATIONS or db2pd -applications)" },
      { flag: "ALL", description: "Force all non-system applications — use with extreme caution" },
    ],
    examples: [
      { command: "db2 \"FORCE APPLICATION (34892)\"", description: "Force a specific application by AppHandle" },
      { command: "LIST APPLICATIONS SHOW DETAIL | grep -i BATCHJOB", description: "First: find the AppHandle of the batch job to force" },
    ],
    relatedConceptIds: ["locking", "transaction-logging", "edu-model"],
    recallScenario: "SQL0964C is firing. db2pd -transactions identifies AppHandle 0-34892 (a batch job) as holding log space for 2 hours. What is the immediate intervention?",
    difficulty: 1,
  },
  {
    id: "reorg-table",
    name: "REORG TABLE",
    fullSyntax: "REORG TABLE <schema>.<table> [INDEX <schema>.<index>] [ALLOW [NO|READ|WRITE] ACCESS] [INPLACE] [LONGLOBDATA]",
    description: "Defragment and recluster table rows. ALLOW WRITE ACCESS (INPLACE) runs online. Classic offline REORG requires exclusive lock.",
    category: "Administration",
    flags: [
      { flag: "INDEX <name>", description: "Recluster rows in index key order" },
      { flag: "ALLOW WRITE ACCESS", description: "Inplace online REORG — table accessible for DML" },
      { flag: "ALLOW READ ACCESS", description: "Allow reads during REORG (classic offline mode with read access)" },
      { flag: "INPLACE", description: "Explicitly request inplace REORG (implies ALLOW WRITE ACCESS)" },
    ],
    examples: [
      { command: "REORG TABLE SCHEMA.ORDERS INDEX SCHEMA.IDX_ORDER_DATE ALLOW WRITE ACCESS", description: "Online inplace REORG clustering by ORDER_DATE index" },
      { command: "REORG INDEXES ALL FOR TABLE SCHEMA.ORDERS ALLOW WRITE ACCESS", description: "Online index-only REORG — rebuild leaf pages" },
    ],
    relatedConceptIds: ["reorg", "statistics", "index-strategy", "tablespace"],
    recallScenario: "REORGCHK shows *** flags on a production table. You cannot take downtime. Describe the REORG command and the tablespace type restriction.",
    difficulty: 2,
  },
  {
    id: "list-utilities",
    name: "LIST UTILITIES",
    fullSyntax: "LIST UTILITIES SHOW DETAIL",
    description: "Show all currently running DB2 utility operations: BACKUP, RESTORE, REORG, LOAD, RUNSTATS. Shows progress and phase.",
    category: "Administration",
    flags: [
      { flag: "SHOW DETAIL", description: "Verbose output including estimated progress and phase" },
    ],
    examples: [
      { command: "LIST UTILITIES SHOW DETAIL", description: "Check if a REORG, BACKUP, or LOAD is currently running and its progress" },
    ],
    relatedConceptIds: ["backup", "reorg", "admin"],
    recallScenario: "A backup started 3 hours ago and you need to check its progress. What command?",
    difficulty: 1,
  },
  {
    id: "get-snapshot",
    name: "GET SNAPSHOT (Legacy)",
    fullSyntax: "GET SNAPSHOT FOR DATABASE ON <name>  /  GET SNAPSHOT FOR ALL APPLICATIONS",
    description: "Legacy snapshot monitoring command (pre-10.5). Still functional but superseded by MON_GET_* table functions. Returns cumulative counters.",
    category: "Monitoring",
    flags: [
      { flag: "FOR DATABASE ON <name>", description: "Database-level snapshot" },
      { flag: "FOR ALL APPLICATIONS", description: "All application snapshots" },
      { flag: "FOR APPLICATION APPHANDLE <n>", description: "Specific application snapshot" },
    ],
    examples: [
      { command: "GET SNAPSHOT FOR DATABASE ON PRODDB | grep -i 'log\\|sort\\|buffer'", description: "Quick check: pipe through grep to filter key metrics" },
    ],
    relatedConceptIds: ["mon-get", "buffer-pool", "transaction-logging"],
    recallScenario: "You're on a DB2 9.7 system (no MON_GET functions). What command gives you database-level metrics?",
    difficulty: 2,
  },
];

export const COMMAND_MAP = new Map(DB2_COMMANDS.map(c => [c.id, c]));
export const COMMAND_CATEGORIES = [...new Set(DB2_COMMANDS.map(c => c.category))];
